code_aug_prepare=com.aaronicsubstances.code.augmentor.ant.PrepareTask
code_aug_process=com.aaronicsubstances.code.augmentor.ant.ProcessTask
code_aug_complete=com.aaronicsubstances.code.augmentor.ant.CompletionTask
code_aug_run=com.aaronicsubstances.code.augmentor.ant.CodeAugmentorTask